all:
  children:
    
    fluentdagr:
      hosts:
        127.0.0.1:
          fluentd_es_hosts: 127.0.0.1

        127.0.0.1:
          fluentd_es_hosts: 127.0.0.1

    esmaster:
      hosts:
        127.0.0.1:
        127.0.0.1:
        127.0.0.1:

    esdata:
      hosts:
        127.0.0.1:
        127.0.0.1:

    kibana:
      hosts:
        127.0.0.1:

    escross:
      hosts:
        127.0.0.1: