FROM fluent/fluentd:edge-debian

USER root

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && gem install \
    {% for dependency in gem_dependencies %}
        {{ dependency }} \
    {% endfor %}
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \

 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

COPY . /etc/fluent/
RUN rm /etc/fluent/Dockerfile

CMD ["fluentd", "-c", "/etc/fluent/fluent.conf"]