---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete mule.prod indices older than 120 days (based on index creation_date).
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mule.prod
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 120
  2:
    action: delete_indices
    description: >-
      Delete mule.test indices older than 20 days (based on index creation_date).
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mule.test
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 20
  3:
    action: delete_indices
    description: >-
      Delete mule.dev indices older than 20 days (based on index creation_date).
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: mule.dev
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 7