---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
#
# Also remember that all examples have 'disable_action' set to True.  If you
# want to use this action as a template, be sure to set this to False after
# copying it.
actions:
  1:
    action: delete_indices
    description: >-
      Delete all indices older than 10 days (based on index name), for all indices not in scope. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: ^(?!\.|.*payengine|.*ods|.*il|.*mule|.*risksuite|.*searchguard|.*curator|.*myc|.*email|.*emailgateway|.*windream|.*reval|.*wlpfo|.*nexus|.*dk|.*mcvisa|.*pos).*$
      exclude:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 10
  2:
    action: shrink
    description: >-
      Shrink selected indices on the node with the most available space.
      Delete source index after successful shrink, then reroute the shrunk
      index with the provided parameters.
    options:
      ignore_empty_list: True
      shrink_node: DETERMINISTIC
      number_of_shards: 1
      number_of_replicas: 1
      shrink_prefix: 
      shrink_suffix: '-shrink'
      delete_after: True
      node_filters:
        permit_masters: False
        exclude_nodes: ['vmfraluxalemn01','vmfraluxalemn02','vmfraluxalemn03','vmfraluxalecc01']
      #post_allocation:
      #  allocation_type: include
      #  key: node_tag
      #  value: cold
      wait_for_active_shards: 1
      extra_settings:
        settings:
          index.codec: best_compression
      wait_for_completion: True
      wait_for_rebalance: True
      wait_interval: 15
      max_wait: -1
    filters:
      - filtertype: pattern
        kind: suffix
        value: '-shrink'
        exclude: True
      - filtertype: age
        source: creation_date
        direction: older
        unit: days
        unit_count: 10