---
  - name: create escross tmp dir
    file:
      path: /tmp/escross
      state: directory

  - name: upload ElasticSearch CrossCluster Search Node container sources
    copy:
      src: "{{ role_path }}/files/"
      dest: /tmp/escross

  - name: upload unicasthosts template
    template:
      src: unicast_hosts.txt.j2
      dest: /tmp/escross/unicast_hosts.txt

  - name: upload dockerfile template
    template:
      src: Dockerfile.j2
      dest: /tmp/escross/Dockerfile

  - name: upload config template
    template:
      src: elasticsearch.yml.j2
      dest: /tmp/escross/elasticsearch.yml

  - name: build ElasticSearch CrossCluster Search docker image
    docker_image:
      path: /tmp/escross
      name: complex-escross
      tag: latest
      state: present
      force: true
      buildargs:
        http_proxy: "{{ proxy_env.http_proxy }}"
        https_proxy: "{{ proxy_env.https_proxy }}"
        no_proxy: "{{ proxy_env.no_proxy }}"
    when: 'proxy_env is defined and "http_proxy" in proxy_env'

  - name: build ElasticSearch CrossCluster Search docker image
    docker_image:
      path: /tmp/escross
      name: complex-escross
      tag: latest
      state: present
      force: true
    when: 'proxy_env is undefined or "http_proxy" not in proxy_env'

  - name: create config mount dir
    file:
      path: /opt/esconfig
      owner: 1000
      group: 1000
      state: directory

  - name: Copy config files to mount dir
    copy: 
      src: "/tmp/escross/{{ item }}"
      dest: "/opt/esconfig/{{ item }}"
      remote_src: yes 
    with_items: 
      - "elasticsearch.yml"
      - "unicast_hosts.txt"
      - "jvm.options"
      - "log4j2.properties"

 #this step can be use with ansible 2.8, eta may 2019
#  - name: copy certs to mount dir
#    copy:
#      src: /tmp/escross/certificates/.
#      dest: /opt/esconfig
#      remote_src: yes 
#      directory_mode: yes

  - name: copy certs to mount dir
    command: "cp -R /tmp/escross/certificates/. /opt/esconfig/"

  - name: set config mount dir permissions
    file:
      path: /opt/esconfig
      owner: 1000
      group: 1000
      state: directory
      recurse: true

  - name: run the ElasticSearch CrossCluster Search Container
    docker_container:
      name: escross
      image: complex-escross:latest
      state: started
      published_ports: 
        - "{{ ansible_ens192.ipv4.address }}:9300:9300"
        - "{{ ansible_ens192.ipv4.address }}:9200:9200"
      restart_policy: unless-stopped
      recreate: true
      volumes: /opt/esconfig:/etc/elasticsearch:rw
      env:
        http_proxy: "{{ proxy_env.http_proxy }}"
        https_proxy: "{{ proxy_env.https_proxy }}"
        no_proxy: "{{ proxy_env.no_proxy }}"
    when: 'proxy_env is defined and "http_proxy" in proxy_env'

  - name: run the ElasticSearch CrossCluster Search Container
    docker_container:
      name: escross
      image: complex-escross:latest
      state: started
      published_ports: 
        - "{{ ansible_ens192.ipv4.address }}:9300:9300"
        - "{{ ansible_ens192.ipv4.address }}:9200:9200"
      restart_policy: unless-stopped
      recreate: true
      volumes: /opt/esconfig:/etc/elasticsearch:rw
    when: 'proxy_env is undefined or "http_proxy" not in proxy_env'

  - name: remove escross tmp dir
    file:
      path: /tmp/escross
      state: absent

  - name: Clean up old docker data
    command: "docker system prune -f"
  - name: Clean up old docker images
    command:  "docker image prune -a -f"
