- name: 'Install the docker daemon'
  yum: 
    name: 'docker-ce-{{ docker_version }}' 
    state: installed 

- name: 'Add docker group'
  group: 
    name: 'docker'
    state: 'present'

- name: Create docker service directory
  file:
    state: directory
    path: /etc/systemd/system/docker.service.d
    mode: 0755

- name: remove Docker Proxy config
  file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: absent
  register: proxy_config_deleted
  when: 'proxy_env is undefined or proxy_env is undefined or "http_proxy" not in proxy_env and "https_proxy" not in proxy_env'

- name: set Docker Proxy config
  template: 
    src: docker-proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  register: proxy_config
  when: 'proxy_env is defined and proxy_env is defined and proxy_env is defined and "http_proxy" in proxy_env and "https_proxy" in proxy_env'

- name: add daemon.json
  copy:
    src: "{{ role_path }}/files/daemon.json"
    dest: /etc/docker/daemon.json
  register: daemon_json

- name: Restart systemctl
  systemd:
    daemon_reload: yes
  when: proxy_config.changed or proxy_config_deleted.changed

- name: Restart docker
  systemd:
    name: docker
    state: restarted
  when: proxy_config.changed or proxy_config_deleted.changed or daemon_json.changed
